---
- hosts: database
  become: true
  tasks:
    - name: install apt packags
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - mysql-server
        - python-mysqldb

    - name: ensure mysql started
      service: name=mysql state=started enabled=yes

    - name: ensure mysql listening on all ports
      lineinfile:
        dest=/etc/mysql/my.cnf
        regexp=^bind-address
        line="bind-address = 0.0.0.0"
      notify: restart mysql

    - name: create demo database
      mysql_db:
        name=demo
        state=present

    - name: create demo user
      mysql_user:
        name=demo
        state=present
        password=demo
        priv=demo.*:ALL
        host='%'

  handlers:
    - name: restart mysql
      service:
        name=mysql
        state=restarted
