---
# Bring stack down
- hosts: loadbalancer
  become: true
  tasks:
    - name: loadbalancer stop nginx
      service:
        name=nginx
        state=stopped
    - name: wait for nginx to be down
      wait_for:
        port=80
        state=drained

- hosts: webserver
  become: true
  tasks:
    - name: webserver stop apache2
      service:
        name=apache2
        state=stopped
    - name: wait for apache2 to be stopped
      wait_for:
        port=80
        state=stopped

# Restart mysql
- hosts: database
  become: true
  tasks:
    - name: mysql restart
      service:
        name=mysql
        state=restarted
    - name: wait for database to come back online
      wait_for:
        host={{ ansible_eth1.ipv4.address }}
        port=3306

# Bring stack up
- hosts: webserver
  become: true
  tasks:
    - name: webserver start apache2
      service:
        name=apache2
        state=started
    - name: wait for apache2 to start
      wait_for: port=80

- hosts: loadbalancer
  become: true
  tasks:
    - name: loadbalancer start nginx
      service:
        name=nginx
        state=started
    - name: wait for nginx loadbalancer to start
      wait_for: port=80

