---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verify nginx service running
      command: service nginx status

    - name: verify nginx listening on port 80
      wait_for:
        port=80
        timeout=1

- hosts: webserver
  become: true
  tasks:
    - name: verify apache2 service running
      command: service apache2 status

    - name: verify apache2 listening on port 80
      wait_for:
        port=80
        timeout=1

- hosts: database
  become: true
  tasks:
    - name: verify mysql service running
      command: service mysql status

    - name: verify mysql listening on port 3306
      wait_for:
        port=3306
        timeout=1




