---
# Bring stack down
- hosts: loadbalancer
  become: true
  tasks:
    - name: loadbalancer stop nginx
      service: name=nginx state=stopped

- hosts: webserver
  become: true
  tasks:
    - name: webserver stop apache2
      service: name=apache2 state=stopped

# Restart mysql
- hosts: database
  become: true
  tasks:
    - name: mysql restart
      service: name=mysql state=restarted

# Bring stack up
- hosts: webserver
  become: true
  tasks:
    - name: webserver start apache2
      service: name=apache2 state=started

- hosts: loadbalancer
  become: true
  tasks:
    - name: loadbalancer start nginx
      service: name=nginx state=started

